### ISSUE TITLE
Bad popup position on mobile

### ISSUE THREAD

**Issue by kylejwatson** [longjiang/zerotohero-cli#2]
When clicking a link that gets translated the translation persists when the next page is loaded but is in a bad position.
In the attachment I had clicked on 'study' to get to that page.
![Screenshot_20191029-105217_Brave](https://user-images.githubusercontent.com/5176836/67761092-8355db80-fa3a-11e9-9117-5a30bd58243e.jpg)

**Comment by longjiang** [comment]
Oh no... hopefully this has already been fixed on our new site: panlingo.org
