### ISSUE TITLE
No license

### ISSUE THREAD

**Issue by Daja177** [longjiang/zerotohero-cli#4]
This repository doesn't seem to have a license currently. See https://choosealicense.com/no-permission/ for information regarding why this is an issue.

**Comment by Daja177** [comment]
Please consider adding a license to the project whenever possible @longjiang.

**Comment by darxkies** [comment]
Are there any plans regarding adding a license file?

**Comment by longjiang** [comment]
Oops Sorry for taking so long to reply to your email

Sure I can add a license...

Which one do you recommend?



Jon Long 龙江, Designer



Web: www.voxelcreative.ca
Mobile: +1 604 442 4421 | Skype ID: longjiangg
WeChat: longjiang2005bby | LinkedIn | Flickr

**Comment by darxkies** [comment]
Personally I am a fan of GPL. If your work is changed and distributed, the changes have to be made publicly available, so that everyone can benefit from the changes including you. Meaning that your work and any changes from any third party remain freely available to anyone.

**Comment by danspinola** [comment]
His might help. 

https://choosealicense.com

https://tldrlegal.com/

**Comment by longjiang** [comment]
Oh hi... sorry for the very late reply. We've actually moved the project to panlingo.org with the new repo https://github.com/longjiang/panlang-nuxt (we now use Nuxt so we get SSR). The repo has an MIT license.

Thanks for all your input!
