### ISSUE TITLE
Dictionary images broken

### ISSUE THREAD

**Issue by teegee** [longjiang/zerotohero-cli#6]
Just in case you hadn't noticed, dictionary entries in en/zh have some broken images. For example, [this](https://www.zerotohero.ca/en/zh/dictionary/hsk-cedict/%E8%B3%87%E6%96%99,z%C4%AB_li%C3%A0o,0). Worked fine a few days ago.

**Comment by longjiang** [comment]
Oh yeah, I forgot to upload the images after we moved servers... thanks for reminding me

**Comment by teegee** [comment]
No worries, everything has worked fine again the last few days :)
