### ISSUE TITLE
Error in payment with a country code 'KR'

### ISSUE THREAD

**Issue by Seyun** [longjiang/zerotohero-cli#7]
I tried to enroll for a course but failed.

Steps
1. Choose the course of HSK 7-9 words
2. Select 'GPay'
3. An error msg is shown (see below)

Error Message
Invalid value for paymentRequest(): country should be one of the following strings: AE, AT, AU, BE, BG, BR, CA, CH, CI, CR, CY, CZ, DE, DK, DO, EE, ES, FI, FR, GB, GI, GR, GT, HK, HU, ID, IE, IN, IT, JP, LI, LT, LU, LV, MT, MX, MY, NL, NO, NZ, PE, PH, PL, PT, RO, SE, SG, SI, SK, SN, TH, TT, US, UY. You specified: KR.

<img width="777" alt="Screen Shot 2021-04-16 at 3 02 15 PM" src="https://user-images.githubusercontent.com/616384/114979127-49de8d80-9ec5-11eb-9c98-aa88b8144b0d.png">

**Comment by Seyun** [comment]
FYI, I did it later with my credit card.

**Comment by longjiang** [comment]
Ah... thanks so much for letting us know. You're actually not looking at zerotohero, you're looking at a page on Teachable (where we host our courses). I'll let teachable know. Thanks Seyun
